---
title: "Module Trait Correlation"
output: rmarkdown::html_vignette
description: >
  Tutorial for identifying relationships between scWGCNA modules with biological and technical variables.
vignette: >
  %\VignetteIndexEntry{Module Trait Correlation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


Load the snRNA-seq data and the required libraries:
```{r eval=FALSE}

# single-cell analysis package
library(Seurat)

# plotting and data science packages
library(tidyverse)
library(cowplot)
library(patchwork)

# co-expression network analysis packages:
library(WGCNA)
library(scWGCNA)

# network analysis & visualization package:
library(igraph)

# packages for TF motif analysis
library(JASPAR2020)
library(motifmatchr)
library(TFBSTools)
library(EnsDb.Hsapiens.v86)
library(GenomicRanges)

# using the cowplot theme for ggplot
theme_set(theme_cowplot())

# set random seed for reproducibility
set.seed(12345)

# load the Zhou et al snRNA-seq dataset
seurat_ref <- readRDS('data/Zhou_control.rds')

```

Compute module trait correlation split by cell type:

```{r eval=FALSE}


seurat_obj$Sample <- factor(as.character(seurat_obj$Sample), levels=unique(seurat_obj$Sample))
seurat_obj$msex <- as.factor(seurat_obj$msex)
seurat_obj$age_death <- as.numeric(seurat_obj$age_death)

cur_traits <- c('Sample', 'total_counts_mt', 'n_genes_by_counts', 'age_death', 'braaksc', 'msex')
data_types <- sapply(cur_traits, function(x){class(seurat_obj@meta.data[,x])})

cur_traits <- c('braaksc', 'pmi', 'msex')

seurat_obj <- ModuleTraitCorrelation(
  seurat_obj,
  traits = cur_traits,
  group.by='cell_type'
)

temp <- GetModuleTraitCorrelation(seurat_obj)
cor_list <- temp[[1]]
names(cor_list)


```

Plot the results as a heatmap for each cell type:

```{r eval=FALSE}


plot_list <- list()
for(i in names(cor_list)){
  cor_mat <- cor_list[[i]]
  print(i)

  plot_df <- reshape2::melt(cor_mat)
  colnames(plot_df) <- c("Trait", "Module", "cor")

  plot_list[[i]] <- ggplot(plot_df, aes(x=Module, y=Trait, fill=cor)) +
    geom_tile() +
    scale_fill_gradient2(limits=c(-1,1)) +
    RotatedAxis() + ylab('') + xlab('') + ggtitle(i)

}

```
